server:
  port: 8080
  servlet:
    context-path: /


logging:
  config: "classpath:logger/logback/logback-${spring.profiles.active}.xml"
  level:
    org:
      apache:
        zookeeper: INFO
        curator: INFO
    ROOT: INFO
  path: /data/logs/kevinlyz